Repository allen-cell-animated/vole-app, pull requests merged in 2024-08, with the labels that each got.

#299 feat: Store and load camera info from the URL
  package-lock.json
  package.json
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/App/types.ts
  src/aics-image-viewer/components/ViewerStateProvider/index.tsx
  src/aics-image-viewer/components/ViewerStateProvider/types.ts
  website/components/AppWrapper.tsx
  website/components/Modals/ShareModal.tsx
  website/utils/test/url_utils.test.ts
  website/utils/url_utils.ts
Labels: enhancement

#306 fix: Shorten URLs
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/ChannelsWidget.tsx
  src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
  src/aics-image-viewer/components/ViewerStateProvider/index.tsx
  src/aics-image-viewer/shared/constants.ts
  website/components/Modals/ShareModal.tsx
  website/utils/datatype_utils.ts
  website/utils/test/datatype_utils.test.ts
  website/utils/test/url_utils.test.ts
  website/utils/url_utils.ts
Labels: enhancement, URGENT

#305 feature: Reset defaults button
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/ChannelsWidget.tsx
  src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
  src/aics-image-viewer/components/GlobalVolumeControls.tsx
  src/aics-image-viewer/components/TfEditor/index.tsx
  src/aics-image-viewer/components/ViewerStateProvider/index.tsx
  src/aics-image-viewer/shared/constants.ts
  src/aics-image-viewer/shared/utils/controlPointsToLut.ts
  website/components/Modals/ShareModal.tsx
  website/utils/datatype_utils.ts
  website/utils/test/datatype_utils.test.ts
  website/utils/test/url_utils.test.ts
  website/utils/url_utils.ts
Labels: enhancement

#311 fix: Fix bug where unspecified camera in URL would cause black screen in Y slice mode.
  src/aics-image-viewer/shared/constants.ts
  website/utils/test/url_utils.test.ts
  website/utils/url_utils.ts
Labels: bug

#314 feat: Added GTM tag to 3DVV
  public/index.html
Labels: enhancement

#316 update broken urls
  website/components/LandingPage/content.tsx
Labels: bug, priority, URGENT

#312 fix: Shorten ramp and slice parameters
  website/utils/test/url_utils.test.ts
  website/utils/url_utils.ts
Labels: bug
