Repository allen-cell-animated/vole-app, pull requests merged in 2024-05, with the labels that each got.

#219 refactor: Upgrade Ant version
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/index.tsx
  src/aics-image-viewer/assets/icons/dropdownArrow.svg
  src/aics-image-viewer/assets/icons/index.ts
  src/aics-image-viewer/assets/styles/variables.css
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/AxisClipSliders/index.tsx
  src/aics-image-viewer/components/AxisClipSliders/styles.css
  src/aics-image-viewer/components/BottomPanel/index.tsx
  src/aics-image-viewer/components/BottomPanel/styles.css
  src/aics-image-viewer/components/CellViewerCanvasWrapper/index.tsx
  src/aics-image-viewer/components/ChannelsWidget/styles.css
  src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
  src/aics-image-viewer/components/ControlPanel/index.tsx
  src/aics-image-viewer/components/ControlPanel/styles.css
  src/aics-image-viewer/components/MetadataViewer/index.tsx
  src/aics-image-viewer/components/MetadataViewer/styles.css
  src/aics-image-viewer/components/StyleProvider/index.tsx
  src/aics-image-viewer/components/StyleProvider/styles.css
  src/aics-image-viewer/components/Toolbar/DownloadButton.tsx
  src/aics-image-viewer/components/Toolbar/index.tsx
  src/aics-image-viewer/components/Toolbar/styles.css
  src/aics-image-viewer/components/shared/NumericInput/index.tsx
  src/aics-image-viewer/components/shared/NumericInput/styles.css
  src/aics-image-viewer/components/shared/ViewerIcon.tsx
  src/aics-image-viewer/styles/ant-vars.less
  webpack.common.js
  website/components/ErrorPage.tsx
  website/components/Header.tsx
  website/components/LandingPage/index.tsx
Labels: enhancement, Tech Debt, priority

#224 feature: Load menu
  package-lock.json
  package.json
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/StyleProvider/index.tsx
  website/components/AppWrapper.tsx
  website/components/LandingPage/index.tsx
  website/components/LoadModal.tsx
  website/components/MiddleTruncatedText.tsx
  website/utils/react_utils.ts
  website/utils/url_utils.ts
Labels: enhancement

#228 feature: Share URL button
  src/aics-image-viewer/components/StyleProvider/index.tsx
  website/components/AppWrapper.tsx
  website/components/LandingPage/index.tsx
  website/components/ShareModal.tsx
Labels: enhancement

#226 fix: Remove hash routing on GitHub pages
  .github/workflows/aws-deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  .gitignore
  package.json
  public/Globals.d.ts
  public/gh-reroute/404.html
  public/gh-reroute/index.tsx
  public/index.html
  public/index.tsx
  webpack.common.js
  website/utils/gh_route_utils.ts
  website/utils/test/gh_route_utils.test.ts
Labels: bug

#233 fix: Fixed auto-close preventing the side panel from reopening
  src/aics-image-viewer/components/App/index.tsx
Labels: bug

#232 feature: Help menu implementation
  src/aics-image-viewer/components/ControlPanel/index.tsx
  src/aics-image-viewer/components/StyleProvider/index.tsx
  src/aics-image-viewer/components/Toolbar/index.tsx
  website/components/AppWrapper.tsx
  website/components/Buttons/index.tsx
  website/components/HelpDropdown.tsx
  website/components/LandingPage/index.tsx
Labels: enhancement

#234 fix: Incorrect font in embedded viewer
  public/index.tsx
  src/aics-image-viewer/assets/styles/globals.css
  src/aics-image-viewer/assets/styles/typography.css
  src/aics-image-viewer/components/StyleProvider/index.tsx
Labels: bug

#237 fix: Updated histogram on T/Z change
  src/aics-image-viewer/components/TfEditor/index.tsx
Labels: bug

#236 fix: Fix initial URL parameters being ignored
  website/components/AppWrapper.tsx
Labels: bug

#240 Restructure channel settings internals
  src/aics-image-viewer/components/ChannelsWidget.tsx
  src/aics-image-viewer/components/ChannelsWidget/index.tsx
  src/aics-image-viewer/components/ChannelsWidget/styles.css
  src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
  src/aics-image-viewer/components/ChannelsWidgetRow/styles.css
  src/aics-image-viewer/components/ControlPanel/index.tsx
  src/aics-image-viewer/components/ControlPanel/styles.css
  src/aics-image-viewer/components/CustomizeWidget.tsx
  src/aics-image-viewer/components/GlobalVolumeControls.tsx
  src/aics-image-viewer/components/MetadataViewer/styles.css
  src/aics-image-viewer/components/StyleProvider/index.tsx
  src/aics-image-viewer/components/Toolbar/styles.css
  src/aics-image-viewer/components/shared/SharedCheckBox.tsx
Labels: enhancement, Tech Debt

#245 fix: Fixed colorizer and w3cv overwriting the others' recent datasets
  website/utils/react_utils.ts
Labels: bug

#251 fix: Fix GH Pages missing build files
  package.json
Labels: bug, priority

#253 feat: Use new URL parameter schema
  public/firebase/configure-firebase.ts
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/ChannelsWidget.tsx
  src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
  src/aics-image-viewer/shared/utils/controlPointsToLut.ts
  src/aics-image-viewer/shared/utils/viewerChannelSettings.ts
  website/utils/test/url_utils.test.ts
  website/utils/url_utils.ts
Labels: enhancement, priority
