Repository allen-cell-animated/vole-app, pull requests merged in 2024-10, with the labels that each got.

#327 refactor: Automatic import sorting
  .prettierrc
  package-lock.json
  package.json
Labels: enhancement

#326 feat: Updated PR format, added PR previews
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/nightly.yml
  .github/workflows/pr-preview.yml
Labels: documentation

#330 refactor to allow multiple channel settings changes in one
  src/aics-image-viewer/components/App/index.tsx
  src/aics-image-viewer/components/ChannelsWidget.tsx
  src/aics-image-viewer/components/ChannelsWidgetRow/index.tsx
  src/aics-image-viewer/components/TfEditor/index.tsx
  src/aics-image-viewer/components/ViewerStateProvider/index.tsx
  src/aics-image-viewer/components/ViewerStateProvider/types.ts
Labels: priority

#333 fix: Channels are no longer renamed
  src/aics-image-viewer/shared/utils/viewerState.ts
Labels: bug
